export async function GET() {
  const products = [
    {
      id: 1,
      name: "Iphone 15 pro max",
      price: 34990000,
      imageDetail: "/detail-ip15.jpg",
      image: "/iphone-15-pro-max.webp",
      specs:
        "iPhone 15 Pro Max là một chiếc điện thoại thông minh cao cấp được mong đợi nhất năm 2023. Với nhiều tính năng mới và cải tiến, iPhone 15 Pro Max chắc chắn sẽ là một lựa chọn tuyệt vời cho những người dùng đang tìm kiếm một chiếc điện thoại có hiệu năng mạnh mẽ, camera chất lượng và thiết kế sang trọng.",
      display: "Màn hình: OLED6.7, Super Retina XDR",
      operatingSystem: "Hệ điều hành: iOS 17",
      rearCamera: "Camera sau: Chính 48 MP & Phụ 12 MP, 12 MP",
      frontCamera: "Camera trước: 12 MP",
      chip: "Chip: Apple A17 Pro 6 nhân",
      ram: "RAM: 8 GB",
      storage: "Dung lượng: 256 GB",
      Pin: "Pin và sạc: 4422 mAh, 20 W",
    },
    {
      id: 2,
      name: "Samsung Galaxy S23 Ultra",
      price: 25000000,
      imageDetail: "/detail-samsung-s23.jpg",
      image: "/samsung-galaxy-s23.webp",
      specs:
        "Samsung Galaxy S23 Ultra 5G 256GB là chiếc smartphone cao cấp nhất của nhà Samsung, sở hữu cấu hình không tưởng với con chip khủng được Qualcomm tối ưu riêng cho dòng Galaxy và camera lên đến 200 MP, xứng danh là chiếc flagship Android được mong đợi nhất trong năm 2023.",
      display: "Màn hình: Dynamic AMOLED 2X, 6.8'', Quad HD+ (2K+)",
      operatingSystem: "Hệ điều hành: Android 13",
      rearCamera: "Camera sau: Chính 200 MP & Phụ 12 MP, 10 MP, 10 MP",
      frontCamera: "Camera trước: 12 MP",
      chip: "Chip: Snapdragon 8 Gen 2 for Galaxy",
      ram: "RAM: 8 GB",
      storage: "Dung lượng: 256 GB",
      Pin: "Pin và sạc: 5000 mAh, 45 W",
    },
    {
      id: 3,
      name: "Xiaomi 14 Ultra",
      price: 29990000,
      imageDetail: "/detail-xiaomi-14-ultra.jpg",
      image: "/xiaomi-14-ultra.jpg",
      specs:
        "Xiaomi một lần nữa tái định nghĩa sự hoàn hảo trong ngành công nghệ di động với dòng sản phẩm mới nhất của mình, Xiaomi 14 Ultra. Đây không chỉ là một thiết bị thông minh mà còn là một tác phẩm nghệ thuật, chứa đựng trong mình những đột phá về mọi mặt từ thiết kế cho đến hiệu suất.",
      display: "Màn hình: AMOLED6.73'', Quad HD+ (2K+)",
      operatingSystem: "Hệ điều hành: Android 14",
      rearCamera: "Camera sau: 4 camera 50 MP",
      frontCamera: "Camera trước: 32 MP",
      chip: "Chip: Snapdragon 8 Gen 3 8 nhân",
      ram: "RAM: 16 GB",
      storage: "Dung lượng: 512 GB",
      Pin: "Pin và sạc: 5000 mAh, 90 W",
    },
    {
      id: 4,
      name: "OPPO Find N3",
      price: 41990000,
      imageDetail: "/detail-oppo-find-n3.jpg",
      image: "/oppo-find-n3.webp",
      specs:
        "OPPO chính thức giới thiệu sản phẩm OPPO Find N3 5G, một chiếc điện thoại thông minh với thiết kế gập ngang hoàn toàn hiện đại và đẳng cấp, nổi bật với camera và hiệu năng đứng đầu. Đây là một bước đột phá của OPPO trong việc kết hợp sự tiện ích và thẩm mỹ tối ưu, đem lại trải nghiệm độc đáo cho người dùng.",
      display: "AMOLED, Chính 7.82'' & Phụ 6.31'', Quad HD+ (2K+)",
      operatingSystem: "Hệ điều hành: Android 13",
      rearCamera: "Camera sau: Chính 48 MP & Phụ 48 MP, 64 MP",
      frontCamera: "Camera trước: 20 MP & Ngoài: 32 MP",
      chip: "Chip: Snapdragon 8 Gen 2 8 nhân",
      ram: "RAM: 16 GB",
      storage: "Dung lượng: 512 GB",
      Pin: "Pin và sạc: 4805 mAh, 67 W",
    },
    {
      id: 5,
      name: "Realme 11 Pro+ 5G",
      price: 13990000,
      imageDetail: "/detail-realme-11-pro-plus.jpg",
      image: "/realme-11-pro-plus.jpg",
      specs:
        "realme 11 Pro+ 5G mẫu điện thoại kinh doanh chính hãng tại thị trường Việt Nam vào tháng 07/2023, máy được cộng đồng người yêu công nghệ quan tâm nhiều nhờ sở hữu cấu hình mạnh mẽ, thiết kế đẹp và còn trang bị hệ thống ống kính xịn với độ phân giải cao nhất lên đến 200 MP.",
      display: "Màn hình: AMOLED, 6.7'', Full HD+",
      operatingSystem: "Hệ điều hành: Android 13",
      rearCamera: "Camera sau: Chính 200 MP & Phụ 8 MP, 2 MP",
      frontCamera: "Camera trước: 32 MP",
      chip: "Chip: MediaTek Dimensity 7050 5G 8 nhân",
      ram: "RAM: 12 GB",
      storage: "Dung lượng: 512 GB",
      Pin: "Pin và sạc: 5000 mAh, 100 W",
    },
    {
      id: 6,
      name: "vivo V30 5G",
      price: 13990000,
      imageDetail: "/detail-vivo-v30.jpg",
      image: "/vivo-v30-5g.webp",
      specs:
        "vivo V30 kết hợp thiết kế sang trọng, hiệu suất vượt trội và hệ thống camera đỉnh cao, mang đến trải nghiệm người dùng toàn diện. Với nhiều tính năng tiên tiến và thiết kế tinh tế, vivo V30 5G không chỉ đáp ứng nhu cầu công nghệ hằng ngày mà còn nâng tầm phong cách và tiện nghi cho người dùng.",
      display: "Màn hình: AMOLED, 6.78'', 1.5K",
      operatingSystem: "Hệ điều hành: Android 14",
      rearCamera: "Camera sau: Chính 50 MP & Phụ 50 MP",
      frontCamera: "Camera trước: 50 MP",
      chip: "Chip: Snapdragon 7 Gen 3 8 nhân",
      ram: "RAM: 12 GB",
      storage: "Dung lượng: 512 GB",
      Pin: "Pin và sạc: 5000 mAh, 80 W",
    },
    {
      id: 7,
      name: "ZTE nubia Red Magic 8 Pro Plus",
      price: 16099000,
      imageDetail: "/detail-red-magic-8.jpg",
      image: "/red_magic_8_pro_plus.webp",
      specs:
        "Dòng Red Magic 8 Pro và 8 Pro+ có hầu hết các tính năng tương tự nhau. Cả hai đều được trang bị chip Snapdragon 8 Gen 2 mới nhất và tốt nhất của Qualcomm, đi kèm với thanh RAM khủng lên đến 12 GB và bộ nhớ trong lên đến 256 GB trên phiên bản 8 Pro và trên phiên bản 8 Pro+ sẽ là thanh RAM lên đến 16 GB và bộ nhớ trong lên đến 1 TB.",
      display: "Màn hình: 6.8 inches, AMOLED, 1B colors, 120Hz",
      operatingSystem: "Hệ điều hành: Android 13",
      rearCamera: "Camera sau: 50 MP + 8 MP + 2 MP",
      frontCamera: "Camera trước: 16 MP",
      chip: "Chip: Snapdragon 8 Gen 2",
      ram: "RAM: 12 GB",
      storage: "Dung lượng: 256 GB",
      Pin: "Pin và sạc: 5000 mAh, 165 W",
    },
    {
      id: 8,
      name: "HONOR X8b",
      price: 7690000,
      imageDetail: "/detail-honor-x8b.jpg",
      image: "/honor-x8b.webp",
      specs:
        "Trên thị trường điện thoại thông minh, HONOR tiếp tục khẳng định vị thế của mình với việc giới thiệu HONOR X8b, một thiết bị không chỉ tuân theo xu hướng thiết kế hiện đại mà còn cung cấp những tính năng nổi bật phục vụ mọi nhu cầu của người dùng.",
      display: "Màn hình: AMOLED, 6.7'', Full HD+",
      operatingSystem: "Hệ điều hành: Android 13",
      rearCamera: "Camera sau: Chính 108 MP & Phụ 5 MP, 2 MP",
      frontCamera: "Camera trước: 50 MP",
      chip: "Chip: Snapdragon 680",
      ram: "RAM: 8 GB",
      storage: "Dung lượng: 512 GB",
      Pin: "Pin và sạc: 4500 mAh, 35 W",
    },
  ];

  return Response.json({ products });
}
